### ISSUE TITLE
라이브러리를 찾을수 없다고 합니다!

### ISSUE THREAD

**Issue by Choi-YoungHyun** [teddylee777/langchain-teddynote#1]
안녕하세요. 유튜브 구독자입니다.
유튜브를 보다 위키독스에 Langchain 오픈책을 읽으면서 공부중입니다.

다름이 아니라
pip install langchain-teddynote를 했는데 아래와 같은 에러가 발생합니다.

ERROR: Could not find a version that satisfies the requirement langchain-teddynote (from versions: none)

colab에선 정상적으로 되는데 혹시 window버전이 다른가 해서 여쭤봅니다.
그냥 clone할까도 했지만 궁금해서 여쭤봅니다.

저의 환경입니다.
OS= window 10
Python = 3.9.7

**Comment by teddylee777** [comment]
@Choi-YoungHyun 님 안녕하세요?

본 라이브러리는 python 3.10 이상 환경에서만 설치가 가능합니다! (setup.py 에서 확인하실 수 있어요)

감사합니다.
